version: "2"
services:
  app:
    environment:
      - WEATHER_API_KEY=${API_KEY}
    container_name: app
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"